packages:
  - 'support/templates/*'
  - 'packages/@remirror/*'
  - 'packages/*'
  - 'support'
  - 'support/deprecated/*'
  - 'support/e2e'
  - 'support/storybook'
  - 'support/website'
  - 'examples/*'
  - 'backend/*'
